- setup.py
With Python 2.7 and django-guardian 1.3, tests on CentOS/Fedora were
failing with: "DoesNotExist: ContentType matching query does not exist."
> Updated django-guardian dependency to fix test errors with Python 2.7.

- resolwe/flow/views.py
Previously, no permissions were assigned to the object contributor when an object was created via the REST API.
> Assign all permissions to the object contributor

- resolwe/flow/views.py
Otherwise, the object might already be created but without permissions, which introduces a race condition with the query observers.
> Ensure that permissions are assigned atomically

- resolwe/flow/management/commands/genesis_migrate.py
- resolwe/flow/models.py
Since d054afc76fd00f561b1766a45797797082cc3d11 the import process from the old system (`genesis_migrate`) is completely broken (some issues are introduced by that commit and some are just exposed by it). This pull request fixes some obvious issues with the mentioned commit, but there is also another problem.
Importing a dump currently fails with the following error when calling `hydrate_input_references`:
```
ValueError: invalid literal for int() with base 10: '54f70fb6fad58d20240baf97'
```
The issue seems to be that `render_descriptor` tries to resolve the references to imported data objects, but the Data's input JSON itself is not migrated at all, so all references are wrong. The migration process should also recursively fix the references before loading objects. But since Data objects …
> Fixes for render_descriptor

- resolwe/flow/serializers.py
This is required as all API views need to provide primary keys in order for them to be usable by the query observers. For some reason, the primary key (field `id`) was not provided with Process serializer.
> Include primary key when serializing Process

- resolwe/flow/tests/__init__.py
- resolwe/flow/tests/test_test_framework.py
Extend `ProcessorTestCase.assertFiles()` with a filter parameter that is a function for filtering the contents of output files.
Add two test cases for this new feature.
> Add ability to filter lines when comparing test output files

- setup.py
The latest version (3.3.3) fails to install on Read the Docs.
I've reported the bug to upstream: https://github.com/rtfd/readthedocs.org/issues/2101.
> Pin Django REST Framework's version to 3.3.2 to fix Read the Docs

- resolwe/flow/migrations/0004_autoslug_field.py
- resolwe/flow/models.py
The previous one shrunk the `slug` field to 50 characters, while it was 100 before. This causes failures when migrating old data.
> Fix broken migration to AutoSlugField

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker.py
- resolwe/flow/executors/local.py
- tests/settings.py
Use it by specifying the `FLOW_EXECUTOR['COMMAND']` setting.
Change test project's settings to allow setting a custom executor command via `RESOLWE_EXECUTOR_COMMAND` environment variable.
> Add ability to use a custom executor command

- docs/CHANGELOG.rst
- resolwe/flow/tests/__init__.py
The `assertFileExists` function is [already used by downstream project Resolwe Bioinformatics](https://github.com/genialis/resolwe-bio/search?utf8=%E2%9C%93&q=assertFileExists).
The old function (`assertFileExist`) was [not used by Resolwe project](https://github.com/genialis/resolwe/search?utf8=%E2%9C%93&q=assertFileExist) or [Resolwe Bioinformatics project](https://github.com/genialis/resolwe-bio/search?utf8=%E2%9C%93&q=assertFileExist)
> Rename assertFileExist to assertFileExists

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker.py
- resolwe/flow/executors/local.py
- resolwe/flow/tests/test_executors.py
Improve handling of the case when Docker is not available.
> Use FLOW_EXECUTOR['COMMAND'] everywhere

- docs/CHANGELOG.rst
- resolwe/flow/tests/test_executors.py
To test the skip conditions of the `check_docker()` function, do the following:
1. `RESOLWE_EXECUTOR_COMMAND='dockerbla' ./tests/manage.py test -v 2 resolwe.flow.tests.test_executors.DockerExecutorTestCase`
This should return something like:
`test_run_in_docker (resolwe.flow.tests.test_executors.DockerExecutorTestCase) ... skipped u"Docker command 'dockerbla' not found"`
2. `RESOLWE_EXECUTOR_COMMAND='docker bla' ./tests/manage.py test -v 2 resolwe.flow.tests.test_executors.DockerExecutorTestCase`
This should return something like:
`test_run_in_docker (resolwe.flow.tests.test_executors.DockerExecutorTestCase) ... skipped u"Docker command 'docker bla info' returned non-zero exit status"`
@mstajdohar: The `check_docker()` code is more complex but more Pythonic - it's a trade-off. It will be …
> Small cleanup

- setup.py
The latest version (0.5.0) causes test failures:
https://ci.genialis.com/job/resolwe-master/141/testReport/
> Pin django-versionfield2's version to 0.4.0

- resolwe/flow/tests/test_test_framework.py
- resolwe/flow/utils/test.py
Fix for error:
`  File "/Users/janez/resolwe/resolwe/flow/utils/test.py", line 442, in _debug_info
msg += fn.read()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2017: ordinal not in range(128)`
> Make ProcessTestCase._debug_info() robust to non-ascii stdout.txt

- setup.py
Use packages' official capitalization (e.g. Django instead of django).
> Update Django requirement for security fixes

- setup.py
Required due to upstream bug:
https://github.com/neithere/django-autoslug/pull/18
> Use our fork of django-autoslug for now

- README.rst
- docs/contributing.rst
- setup.py
- tox.ini
Add `--process-dependency-links` to Tox commands and documentation.
Specify an exact version of django-autoslug and change it to `1.9.4-dev` so that it matches the actual version used by our fork.
> Ensure we really use our fork of django-autoslug

- setup.py
The latest version 1.0.0 breaks backwards compatibility.
See: https://github.com/carltongibson/django-filter/blob/4b459cf/docs/guide/migration.txt for details.
> Pin django-filter requirement to version 0.15.3

- MANIFEST.in
- docs/CHANGELOG.rst
- tests/.env
- tests/docker-compose.yml
By default, project name equals the directory name, where `docker-compose.yml` resides.
Since directory name is `tests`, this is prone to clashes with other projects, so we manually set it to `resolwe`.
> Set Docker Compose's project name to 'resolwe' to avoid name clashes

- docs/CHANGELOG.rst
- docs/conf.py
- resolwe/flow/executors/docker.py
- resolwe/flow/tests/test_env_vars.py
- resolwe/flow/tests/test_executors.py
- resolwe/flow/utils/test.py
- setup.py
- tests/settings.py
- tox.ini
Contains:
- Upgrade to Sphinx 1.5.1+
- Remove `RESOLWE_API_HOST` setting from test project's settings since it is not really used anywhere
- Expose `check_docker()` test utility function 
- Add `check_installed()` test utility function
- Add support for configuring the network mode of Docker executor
I think it will be easier to review this commit by commit.
> Preparatory work for adding a custom LiveServerTestCase for process tests that use Resolwe API

- docs/CHANGELOG.rst
- docs/contributing.rst
- resolwe/__about__.py
Fix installation instructions for installing Resolwe from PyPI.
NOTE: Resolwe Bioinformatics was also updated for this in genialis/resolwe-bio#200 PR.
> Prepare release 1.4.1

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker.py
- resolwe/flow/executors/local.py
- resolwe/test/utils.py
- tests/settings.py
The previous approach to setting a custom executor command didn't scale to more that one executor since the custom command was used by all executors. However, during testing one must be able to run some tests via the local executor and some tests via the Docker executor.
There appears to be no need to set a custom command for the local executor, so we only retained the ability to set a custom command for the Docker executor.
Changed test project's settings to allow setting a custom command for the Docker executor via `RESOLWE_DOCKER_COMMAND` environment variable.
> Only retain ability to set a custom command for the Docker executor

- docs/conf.py
Obtain version of the installed Django package and configure intersphinx to create references to its upstream documentation.
> Configure intersphinx to reference the appropriate Django docs

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker.py
This is needed on hosts where SELinux is enabled.
@dblenkus, @mstajdohar, can you please run (one) [process test case in Resolwe Bioinformatics](https://github.com/genialis/resolwe-bio/tree/master/resolwe_bio/tests/processes) with this PR since I'm not sure how this new flag behaves on systems without SELinux.
> Set appropriate SELinux labels when mounting tools in Docker containers

- resolwe/test/testcases.py
Modify CONTAINER_NAME_PREFIX setting in tests to add a random string to container name's prefix to avoid name clashes when tests are run from different Resolwe code bases on the same system.
Note that this should resolve name clashes found during Resolwe Bioinformatics tests on Jenkins.
> Avoid Docker container name clashes when running the tests

- resolwe/toolkit/docker_images/base/Dockerfile
- resolwe/toolkit/docker_images/base/re-import.sh
This is needed since some processes expect re-import to set some environment variables (e.g. `NAME`) after calling it.
> Convert re-import to a Bash function in ~/.bash_profile

- MANIFEST.in
Only include Python files under `resolwe/toolkit/tests`, not the whole `resolwe/toolkit` directory.
Move includes for `Dockerfiles` and files needed to build Docker images together.
> Improve MANIFEST.in

- docs/api.rst
- docs/index.rst
- resolwe/flow/serializers.py
- resolwe/rest/__init__.py
- resolwe/rest/fields.py
- resolwe/rest/projection.py
- resolwe/rest/serializers.py
- resolwe/rest/tests.py
- tox.ini
Adds support for projections like this:
* `data` (top-level projection)
* `name` (top-level projection)
* `descriptor_schema__name` (nested projection)
* `data__name` (nested projection)
* `descriptor_schema__schema__name` (nested projection + projection into JSON field)
* `data__input__reads` (nested projection + projection into JSON field)
* `data__output__bam__file` (nested projection + deep projection into JSON field)
TODO:
> Support field projection via REST API

- docs/CHANGELOG.rst
- resolwe/flow/tests/test_access_api.py
- resolwe/test/__init__.py
- resolwe/test/testcases/__init__.py
- resolwe/test/testcases/process.py
- resolwe/test/utils.py
- setup.py
- tests/settings.py
- Add tests for accessing Resolwe API from a process
- Add `TransactionProcessTestCase` based on `TransactionTestCase`
~~**WIP: If tests are run together with some `resolwe.permissions.test_shortcuts.GetObjectsForUser` tests, they fail.**~~
~~For example:~~
```
(resolwe) [tadej@tlinux64 tests (add-resolwe-api-host-tests)]$ ./manage.py test -v 2 resolwe.flow.tests.test_access_api resolwe.permissions.tests.test_shortcuts.GetObjectsForUser.test_has_any_group_permissions
Creating test database for alias 'default' ('resolwe_test')...
Operations to perform:
Synchronize unmigrated apps: elastic, mathfilters, permissions, resolwe, rest_framework, staticfiles, versionfield
Apply all migrations: auth, contenttypes, flow, guardian, sessions
Synchronizing apps without migrations:
Creating tables... …
```
> Add 'with_custom_executor' and 'with_resolwe_host' test decorators

- .travis.yml
This reverts commit b12516e5c9c217f3e1a452ace53df635ed1e4508.
The issue has been fixed in [setuptools 36.0.1](https://setuptools.readthedocs.io/en/latest/history.html#v36-0-1).
> Revert "Work-around for an issue with the latest setuptools (36.0.0)"

- resolwe/flow/tests/test_manager.py
- resolwe/test/testcases/__init__.py
This also reverts https://github.com/genialis/resolwe/commit/9c6e73c309c08084cbbcf2df724babdf644deeea, which deleted the redundant code in the parent class (`TransactionTestCase`) which caused [various](https://travis-ci.org/genialis/resolwe/jobs/244912493) [random](https://travis-ci.org/genialis/resolwe/jobs/244912495) [Travis](https://travis-ci.org/genialis/resolwe/jobs/244912496) [build](https://travis-ci.org/genialis/resolwe/jobs/244937632) [failures](https://travis-ci.org/genialis/resolwe/jobs/244937633).
> Remove redundant _pre_setup() in TestManager

- tests/settings.py
They are obsolete since we don't use django-jenkins anymore.
> Remove PROJECT_APPS from test Django project's settings

- resolwe/toolkit/docker_images/base/Dockerfile
This version of Fedora coerces the C locale to C.UTF-8 which means Python 3 will have C.UTF-8 set as the default locale.
> Update toolkit's base image to Fedora 26

- resolwe/flow/tests/test_executors.py
- tox.ini
Since commit eb65922 which updated the toolkit's base Docker image to Fedora 26, this test has been [consistently](https://travis-ci.org/genialis/resolwe/builds/254789560) [failing](https://travis-ci.org/genialis/resolwe/builds/254843094) on [Travis CI](https://travis-ci.org/genialis/resolwe/builds/255247548).
Skip the test until we debug the issue.
> Temporarily skip test_memory_resource executor test on Travis CI

- setup.py
- tox.ini
This should fix the current testing issues since the latest urllib3 version (1.22) is incompatible with the latest version of requests (2.18.1):
```
$ pip check
requests 2.18.1 has requirement urllib3<1.22,>=1.21.1, but you have urllib3 1.22.
```
Run `pip check` to detect incompatible dependencies.
> Temporarily pin urllib3 to version 1.12.1

- resolwe/test/utils.py
- resolwe/toolkit/docker_images/archiver/README.md
- resolwe/toolkit/docker_images/upload-tab-file/README.md
Set the fedora-26 tag of the resolwe/base Docker image where it was previously used without a tag.
> Specify tag of the required base Docker image

- docs/CHANGELOG.rst
- resolwe/flow/management/commands/list_docker_images.py
- resolwe/flow/tests/test_commands.py
The `list_docker_images` management command prepares a list of Docker images used by processes (in YAML format, suitable for use in Ansible).
> Add command to list Docker images used by processes

- resolwe/toolkit/docker_images/base/Dockerfile.fedora-26
- resolwe/toolkit/docker_images/base/Dockerfile.ubuntu-14.04
- resolwe/toolkit/docker_images/base/Dockerfile.ubuntu-16.04
Using the root user's `.bash_profile` is very ugly and should be avoided. It may also become unsupported (e.g. will not be evaluated), based on how we implement running as the correct user.
In genialis/resolwe-bio#335 the relevant section will also change to use `/etc/profile.d/resolwebio-legacy.sh` instead. Other Docker images should follow the same naming convention, each creating its own file in `/etc/profile.d`.
> Use /etc/profile.d instead of .bash_profile

- resolwe/flow/tests/processes/tests.yml
- resolwe/toolkit/processes/archiver.yml
- resolwe/toolkit/processes/files.yml
Remove redundant double-quotes when specifying Docker images
> Bump versions of modified toolkit processes

- resolwe/flow/tests/processes/tests.yml
- resolwe/flow/tests/test_commands.py
This commit adds two additional tests for the `list_docker_images`
management command.  It tests sorting of the output and proper handling
of process versions.
> Add additional tests for 'list_docker_images'

- docs/CHANGELOG.rst
- resolwe/test/testcases/__init__.py
Similar to already existing per-process data directories. My suspicion is that using the same upload directory in multiple parallel processes can cause race conditions in SELinux directory relabeling, which may cause containers to fail to start during tests.
In addition, this separation is also needed as otherwise there is another potential race condition when the same filename is used in two concurrent tests. In this case one test may see the upload disappear.
> Use per-process upload dir in tests

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker/__init__.py
- resolwe/flow/tests/processes/tests.yml
- resolwe/flow/tests/test_executors.py
For some reason this wasn't caught by tests, but later caused problems with iClip tests on Jenkins with SELinux enabled.
This should probably be backported to 3.x.
> Relabel temporary user/group files

- docs/CHANGELOG.rst
- resolwe/permissions/mixins.py
Broken because of https://github.com/encode/django-rest-framework/commit/b905197f24a74066e79888c56ddcf676c994cefc#diff-acb883ee0c042314f361a94aa00e5424
> Add current_user_permissions to serializer's fields

- resolwe/elastic/builder.py
I noticed that in some cases `rel` has been renamed to `remote_field` on related fields, but for some reason it is still `rel` in descriptors, so we can't rename that part yet.
> Fix deprecated rel.to attribute

- docs/CHANGELOG.rst
- resolwe/flow/executors/__init__.py
- resolwe/flow/executors/docker/__init__.py
- resolwe/flow/management/commands/list_docker_images.py
- resolwe/flow/management/commands/register.py
- resolwe/test/utils.py
- tests/settings.py
This PR adds the `--pull` option to the `list_docker_images` management command, as well as a `post_register_hook` to the `BaseFlowExecutor` class, which is called by the `register` command after process registration finishes.  This hook is implemented by the Docker executor to pull Docker images.
The WIP part: in its current state, it should work in production, but the tests use the local executor and override it for Docker tests, so the hook is never run.  Working on fixing this at the moment.
> Pull Docker images after process registration is complete

- docs/CHANGELOG.rst
- resolwe/flow/tests/test_access_api.py
- resolwe/flow/tests/test_executors.py
- resolwe/flow/tests/test_manager.py
- resolwe/test/__init__.py
- resolwe/test/testcases/process.py
Remove `ProcessTestCase` that enclosed tests' code in a transaction and rename the non-transactional `TrasactionProcessTestCase` to `ProcessTestCase`.
Remove `ProcessTestCase.run_process`' `run_manager` argument since it no longer applies.
Update `test_executors.ManagerRunProcessTest.test_workflow` test to make it work with non-transactional `ProcessTestCase`.
> Make ProcessTestCase non-transactional

- .travis.yml
- docs/CHANGELOG.rst
- docs/contributing.rst
- resolwe/flow/models/data.py
- resolwe/flow/models/utils.py
- setup.cfg
- setup.py
- tox.ini
Use `python_requires` `setup()` argument to specify the required Python version.
> Drop Python 2 support, require Python 3.4+

- resolwe/test_helpers/test_runner.py
- tests/settings.py
The post-channelization system was to merely append a suffix to the
settings in FLOW_EXECUTOR, so e.g. `test_data/test` was transformed into
`test_data/test_<num>`. If there were no special test settings, e.g.
`resolwe_data/`, this was therefore changed into `resolwe_data_<num>/`,
which is jarring. The new code creates `[setting]/test_<num>`
directories, so there are no weird top-level suffixed siblings.
> Change test directory creation so it always creates a subdirectory

- docs/CHANGELOG.rst
- resolwe/flow/managers/base.py
Suppose two manager instances scan the database at roughly the same
time and enter the checking transaction for the same object. Both get to
the end of the transaction at the same time, having checked that the
object is indeed resolving. Both also add it to their own to-do queues
before exiting the transaction. At the end, exactly one of the
transactions will succeed, because they both affect the same rows, so
the other will roll back, however: the object will still stay in that
manager's queue. This means that both managers will proceed to try to
execute this Data object, even though one of them actually had a failed
status update transaction.
The fix is to make adding to the queue dependent on transaction success
by setting a flag in its transaction.on_commit event.
> Fix race condition when scanning for resolving Data objects

- tox.ini
Tox environments inherit configuration options from their parents so it is not necessary to define a configuration option in a child environment if its value is the same as in its parent environment.
> Remove redundant setting of Tox's extras configuration option

- docs/CHANGELOG.rst
- resolwe/toolkit/docker_images/base/Dockerfile.ubuntu-17.10
- resolwe/toolkit/docker_images/base/README.md
Ubuntu 17.04 reached end of life on 13. 1. 2018, so it is removed from
base images and Ubuntu 17.10 is added instead.
> Switch Docker base image from Ubuntu 17.04 to Ubuntu 17.10

- docs/CHANGELOG.rst
- resolwe/test_helpers/test_runner.py
In case worker initialization fails for any reason, Python's
multiprocessing pool will just keep restarting workers until the pool
fills up. Due to operation ordering in our test runner, this resulted in
test directories being created in what was effectively an infinite loop.
Example: a mistyped import in routing.py. During init, the manager is
asked to drain its control channel. The drain function calls one of the
testing methods in Django Channels, which will then lazily initialize
the backend - and fail. The resulting exception will propagate up the
stack into the multiprocessing module where it will cause worker failure
(early bootstrap immediately calls os._exit() if there are exceptions).
Because there is still work to be done, new workers will be spawned and
the process repeats ad …
> Mitigate parallel test suite startup failure effects

- docs/CHANGELOG.rst
- tests/settings.py
Enable manager prefix overriding from the environment, in case someone wants to run multiple instances of the test suite at once.
> Enable manager prefix overriding from the env

- docs/CHANGELOG.rst
- resolwe/flow/executors/run.py
- resolwe/flow/managers/dispatcher.py
- resolwe/flow/tests/test_executors.py
- resolwe/flow/utils/purge.py
- resolwe/test_helpers/test_runner.py
This prevents the executor from being run twice on the same data directory. In this case, the second executor will abort.
> Use filesystem-level lock for the data directory

- docs/ref.rst
- resolwe/flow/executors/logger.py
- resolwe/utils.py
In addition, prettify `BraceMessage`'s docstring and include Resolwe Utilities in the documentation reference.
> Ensure logging messages in JSONFormater are instatiated to strings

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker/constants.py
- resolwe/flow/executors/docker/run.py
- resolwe/flow/management/commands/list_docker_images.py
- resolwe/flow/management/commands/register.py
- resolwe/test/utils.py
- resolwe/toolkit/processes/archiver.yml
- resolwe/toolkit/processes/files.yml
- tests/settings.py
Tests currently fail because `resolwe/archiver` and `resolwe/upload-tab-file` have no image tag specified (tag `latest` is no longer allowed). We should tag the images and update these processes, perhaps `1.0.0`?
> Container image changes

- tests/docker-compose.yml
This should lower the resources used by the Elasticsearch container.
> Improve Docker Compose configuration for Elasticsearch

- docs/CHANGELOG.rst
- resolwe/elastic/builder.py
- resolwe/elastic/indices.py
- resolwe/elastic/management/commands/__init__.py
- resolwe/elastic/management/commands/elastic_mapping.py
- resolwe/elastic/tests/test_index.py
Also add `elastic_mapping` management command so mappings can be validated manually in a predictable moment.
> Lazily create ES mappings on first push

- .travis.yml
Start using Build Stages.
Add a new Build Stage, release, which can automatically release a versioned Resolwe git tag to PyPI.
Ensure only the `py*` Tox environments which run the actual Resolwe tests get all the services (PostgreSQL, ElasticSearch and Redis). Other environments get none or the ones they need.
Limit `codecov` installation and submission to `py*` Tox environments.
Limit `RESOLWE_*` environment variable setting to `py*` Tox environments and environments that need it.
> Overhaul of the Travis CI configuration

- resolwe/flow/managers/workload_connectors/slurm.py
Change it to `FLOW_SLURM_PARTITION_DEFAULT` so that it shares the same prefix with the `FLOW_SLURM_PARTITION_OVERRIDES` setting and becomes consistent with `FLOW_PROCESS_RESOURCE_*` settings.
> Rename Slurm's default partition setting

- resolwe/test_helpers/test_runner.py
If an unrecoverable exception occured while running a test, and never
got caught (e.g. an unpicklable exception in a parallel test worker),
the listener would not get terminated properly, leading to a hang.
> Fix manager shutdown in the test runner

- resolwe/flow/execution_engines/bash/__init__.py
- resolwe/flow/execution_engines/workflow/__init__.py
- resolwe/flow/management/commands/register.py
- resolwe/flow/utils/docs/autoprocess.py
- resolwe/test_helpers/test_runner.py
This removes YAMLLoadWarning that was caused because of
unspecified loader.
> Specify loader in yaml.load() method

- resolwe/flow/managers/dispatcher.py
- resolwe/flow/managers/listener.py
- resolwe/flow/models/collection.py
- resolwe/flow/models/data.py
- resolwe/flow/models/entity.py
- resolwe/flow/tests/test_models.py
- resolwe/permissions/tests/test_data.py
We used if-else logic to determine if the timetone support is
enabled in settings. Since this logic is already done in
django.utils.timezone.now we only need to import that.
> Simplify imports of mehtod now

- resolwe/elastic/indices.py
- resolwe/elastic/tests/test_index.py
This produces following queries:
```
SELECT "guardian_userobjectpermission"."user_id" FROM "guardian_userobjectpermission" WHERE ("guardian_userobjectpermission"."object_pk" = '2' AND "guardian_userobjectpermission"."permission_id" = (SELECT U0."id" FROM "auth_permission" U0 WHERE (U0."codename"::text LIKE 'view%' AND U0."content_type_id" = 16)));
```
```
SELECT "guardian_groupobjectpermission"."group_id" FROM "guardian_groupobjectpermission" WHERE ("guardian_groupobjectpermission"."object_pk" = '2' AND "guardian_groupobjectpermission"."permission_id" = (SELECT U0."id" FROM "auth_permission" U0 WHERE (U0."codename"::text LIKE 'view%' AND U0."content_type_id" = 16)));
```
```
SELECT (1) AS "a" FROM "guardian_userobjectpermission" WHERE ("guardian_userobjectpermission"."object_pk" = '2' AND …
```
> Optimize queries for retrieving permissions in elastic indices

- docs/CHANGELOG.rst
- resolwe/flow/models/entity.py
- resolwe/flow/serializers/collection.py
- resolwe/flow/serializers/data.py
- resolwe/flow/serializers/entity.py
- resolwe/flow/serializers/fields.py
- resolwe/flow/tests/test_api.py
- resolwe/rest/tests.py
This fix enables the use of `fields` query parameter for DictRelatedField (Process, DescriptorSchema, collection and Entity).
> Add projection to DictRelatedField

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker/run.py
- setup.py
Changes: 
- Update docker run command with --cpus option and remove --cpu-shares option.
This option is available since docker 1.13 and is set to unlimited by default. The cpus is set to the number of cores provided in process object. This limits most processes to single-threaded execution. 
- The default timeout is increased by factor 1.2. Ulimit option becomes unreliable on multithreaded processes, increase in timeout allows for some difference between realtime and measured time.
> Docker cpu limit

- setup.py
Readthedocs build fails because pyasn1 dependency is missing (dependency of service-identity). Pyasn1 package is included in setup.py because this dependency it is not installed automatically.
> Fix readthedocs build by manually including pyasn1

- .readthedocs.yml
- MANIFEST.in
Solves the issue with Read the Docs documentation failing. During the documentation build, instead of specified pyasn1 package, pyasn1-modules is selected instead. As a consequence, pyasn1 package is missing.
We switch to Read the Docs configuration file to work around this issue.
> Add Read the Docs configuration file

- docs/CHANGELOG.rst
- resolwe/process/parser.py
Currently, process registration fails if there is a top level
class definition that does not inherit from
resolwe.process.runtime. This commit fixes this limitation.
Typical case of other top-level classes are custom classes needed
in the run method.
@dblenkus I'd really like to see this fix in the April release. Is it reasonable to expect that i will?
> Enable all top-level class definitions in Python processes

- docs/CHANGELOG.rst
- resolwe/flow/tests/test_ordering.py
- resolwe/flow/views/collection.py
- resolwe/flow/views/data.py
This adds an option to order collections, entities, and data objects by contributor's last name
```
/api/data?limit=3&fields=contributor&ordering=-contributor__last_name
```
> Add ordering by contributor's last name to Collection and Data viewset

- docs/CHANGELOG.rst
- resolwe/flow/filters.py
- resolwe/flow/tests/test_filtering.py
When foreign key does not exist return empty set instead of raising
validation exception.
Also when filtering using list of foreign keys do not raise validation
exception if some foreign keys in the list do not exist.
> Make filtering via foreign key more Django like

- tox.ini
Enable testing for docs, linters, packaging and migrations environments.
Disable skipping checks when interpreter is not found and prevent passing with
silent errors.
> Enable secondary Tox tests

- docs/index.rst
- docs/storage.rst
- resolwe/flow/managers/dispatcher.py
- resolwe/flow/managers/listener.py
- resolwe/storage/tests/storage_credentials_test_connectors.py
- resolwe/storage/tests/test_manager.py
- resolwe/test/utils.py
- resolwe/test_helpers/test_runner.py
- tests/settings.py
When STORAGE_LOCATION or LOCAL_CONNECTOR were not set in settings some
tests have failed. To make sure tests pass without these configuration
entries they were removed from the setting file.
> Fix errors in tests if configuration was not set

- docs/CHANGELOG.rst
- resolwe/flow/filters.py
- resolwe/flow/tests/test_filtering.py
With this filter, you can for example find orphaned data objects:
```
data?collection__isnull=true&entity__isnull=true
```
> Add isnull related lookup filter

- resolwe/flow/executors/collect.py
- resolwe/flow/tests/test_purge.py
When referenced file was in a subdirectory that was not referenced the
file was deleted.
> Fix purge deleting referenced files

- docs/CHANGELOG.rst
- resolwe/flow/serializers/process.py
This should be done long ago, but we realized only now that it is missing.
> Add entity_always_create in Process serializer

- docs/CHANGELOG.rst
- docs/example/example/processes/template_py_process.py
Starting to write a Python process can be daunting, especially for junior developers. While there are example processes in the test files, there is no comprehensive documentation on the subject yet.
Towards this end, I am committing a template of a Python process which would help developers add a process that already includes all necessary components. It also includes some comments on process specifics, available input/output fields, how to access variables, how to run external tools, raise errors etc.
Let me know if location of the template is appropriate within the example. One thing I did not do here is linking to the template from any documentation. If you think this should be done, please recommend from which document this would make most sense (i.e. `proc.rst`?).
> Add Python process template

- docs/CHANGELOG.rst
- resolwe/flow/managers/listener.py
When asked about missing StorageLocation listener checked all depencies
but it should only consider dependencies with kind equal to KIND_IO.
> Fix dependency handling bug in listener

- resolwe/storage/connectors/transfer.py
- resolwe/storage/manager.py
- resolwe/storage/tests/test_manager.py
in corner caes there may exist locations with status set to PREPARING,
UPLOADING or DELETING. These locations must not be counted as active.
Luckily, the bug can not cause data loss even in border-line cases since default location is never deleted.
> When deleting consider only finished locations & add new exception to transfer_exceptions

- docs/CHANGELOG.rst
- resolwe/flow/executors/transfer.py
- resolwe/flow/tests/test_transfer.py
Instead of exception being propagated to the senty it is logger and
processing is aborted.
> Handle errors gracefully while transfering data

- docs/CHANGELOG.rst
- resolwe/flow/executors/docker/run.py
- resolwe/flow/executors/local/run.py
- resolwe/flow/executors/run.py
- resolwe/process/runtime.py
Improvments include:
* wait for (and kill) the process only if it was not yet terminated
* don't wait for process in Docker executor as it is already handled in
the parent function
* don't log error when process is already terminated
* log error if Docker container removal fails
> Improve process termination

- .github/workflows/docker.yml
when commit is tagged. The tag itself is used as a docker image tag.
If the commit is not tagged build the development version of the image.
Additional commit:
- Fix errors and code cleanup
- Explicit separation of development and stable tags
- Push to ECR instead of Docker hub
> Build tagged version of communication container

- resolwe/storage/connectors/s3connector.py
When data was stored on S3 and presigned URL generated signature
version 2, then stardard output could not be fetched (with(signature
could not be matched error).
The solution was to force using signatures of version 4 in S3 connector.
> Fix show standard button in GUI

- resolwe/flow/executors/startup_communication_container.py
- resolwe/flow/executors/startup_processing_container.py
When keep_data flag is set and there was error during processing the
exception was thrown that was not handled.
> Handle exception when uploading data

- resolwe/flow/executors/init_container.py
- resolwe/storage/connectors/baseconnector.py
- resolwe/storage/connectors/localconnector.py
- resolwe/storage/connectors/s3connector.py
- resolwe/storage/connectors/transfer.py
by skipping the hash computation.
> Transfer inputs in init container faster

- docs/CHANGELOG.rst
- resolwe/flow/managers/listener/listener.py
- resolwe/flow/tests/test_executors.py
- resolwe/test_helpers/test_runner.py
Listener uses zmq router socket for connection handling. When second
client connects with already existing identity, its connection is
rejected and responses are sent to the already connected client.
When zmq.ROUTER_HANDOVER is set to 1 the connection to the already
connected  client is closed and the new one is used.
> Prefer new zmq connections with the same identity

- docs/CHANGELOG.rst
- resolwe/flow/managers/listener/python_process_plugin.py
- resolwe/process/tests/processes/python_test.py
- resolwe/process/tests/test_python_process.py
This adds the ability to change descriptor from within the python process.
> Allow to change Entity descriptor in Python process

- resolwe/flow/executors/socket_utils.py
When a shared filesystem is under heavy load it can take a couple of
minutes for it to respond. If the pause is long enough the system will
determine the worker unresponsive and the processing will be terminated.
Increased timeouts will help to mitigate the above issue.
> Increase timeouts before terminating worker

- docs/CHANGELOG.rst
- resolwe/flow/managers/workload_connectors/kubernetes.py
New gp3 storage class has problems and sometimes halts the entire pod.
Until this issue is resolved the old and tested gp2 class will be the
default.
> Make gp2 default EBS storage class

- docs/CHANGELOG.rst
- resolwe/flow/management/commands/runlistener.py
Wait for the future started inside context manager instead of creating
the new one, which causes AssertionError to be thrown on script exit.
> Do not raise exception when exiting runlistener

- docs/CHANGELOG.rst
- resolwe/flow/managers/workload_connectors/kubernetes.py
When docker image name starts with the key in the mapper the matching
part is replaced with the corresponding value.
> Transform docker image names with mapper

- resolwe/storage/models.py
When deleting ReferencedPaths consider only these belonging to the
StorageLocation we are deleting.
> Speed up deleting storage locations

- setup.py
as version >= 0.9.24 is no longer compatible with Python 3.6.
> Pin asteval to 0.9.23

- resolwe/flow/managers/dispatcher.py
- resolwe/flow/managers/workload_connectors/base.py
- resolwe/flow/managers/workload_connectors/celery.py
- resolwe/flow/managers/workload_connectors/kubernetes.py
- resolwe/flow/managers/workload_connectors/local.py
- resolwe/flow/managers/workload_connectors/slurm.py
Then runtime volume can be removed from platform configuration entirely
when not needed, for instance when using Kubernetes workload manager.
> Remove reference to runtime dir in dispatcher

- .github/workflows/docker.yml
- Build configuration for stable containers now only includes release tags, not pre-release tags (a* versions).
- Additional build configuration for staging matches all tags.
> Separate build and push workflow for stable and staging tags

- .github/workflows/docker.yml
Bash would evaluate `[[ false ]]` to `true`, breaking all conditional
statements.
> Fix conditional statements in the docker workflow

- resolwe/storage/connectors/baseconnector.py
- resolwe/storage/connectors/googleconnector.py
- resolwe/storage/connectors/localconnector.py
- resolwe/storage/connectors/s3connector.py
- resolwe/storage/connectors/transfer.py
to avoid creating multiple versions of the object in S3 bucket when
versioning is enabled.
> Set hashes during upload

- resolwe/flow/executors/startup_communication_container.py
- resolwe/storage/migrations/0010_remove_export_paths.py
so references to files in other storages (for example 'upload') are not
stored in the database.
> Store only refecences to files in the data storage

- docs/CHANGELOG.rst
- resolwe/storage/tests/test_views.py
- resolwe/storage/views.py
In UriResolverView, if a pre-signed url was requested for file that
does not exist (or user does not have permission for) an error is
raised. This happens even if only one out of 100 files is missing
or has permission denied.
From now on this is fixed: for failed urls, empty string is
returned and the response is still HTTP 200.
> Do not fail in case of missing files in UriResolverView

- docs/CHANGELOG.rst
- resolwe/flow/managers/workload_connectors/kubernetes.py
it seems the bug in kubernetes python client is not entirely fixed. Until issues with token refresh are entirely resolved the configuration has to be loaded every time
> Fix: load kubertenes configuration every time

- docs/CHANGELOG.rst
- resolwe/observers/models.py
to notify users when objects (without permissions) are created. The method must be called in order to send the signal.
> Add notify_created method on Subscription

- docs/CHANGELOG.rst
- resolwe/observers/models.py
Unsubscribing would sometimes delete observers belonging to other subscriptions.
> Fix observer unsubscribe bug

- docs/CHANGELOG.rst
- resolwe/flow/executors/socket_utils.py
Some commands may take longer that 30 seconds to process. To avoid processing them twice increase the resend timeout to 60 seconds.
BUG-974
> Increase reset timeouts inside processing container

- docs/CHANGELOG.rst
- resolwe/permissions/permissions.py
The query is proxyed to Django default auth backend for staff users and denied for everybody else.
> Fix crash when checking model-level permissions

- docs/CHANGELOG.rst
- resolwe/flow/managers/listener/redis_cache.py
to speed up cache clear in redis
> Use keys instead of scan_iter

- docs/CHANGELOG.rst
- resolwe/flow/managers/workload_connectors/kubernetes.py
- tests/settings.py
It is read from RESOLWE_KUBERNETES_PULL_POLICY environmental variable with default value Always.
> Add FLOW_KUBERNETES_PULL_POLICY setting

- .github/workflows/ci.yml
> Set default timeout for test job on github actions

- docs/CHANGELOG.rst
- resolwe/flow/tests/test_api.py
- resolwe/flow/views/mixins.py
- resolwe/permissions/tests/test_data.py
> Silently ignore nonexisting/without view permission objects when bulk deleting

- resolwe/flow/filters.py
- resolwe/flow/managers/workload_connectors/kubernetes.py
- resolwe/flow/models/annotations.py
- resolwe/flow/models/storage.py
- resolwe/permissions/filters.py
- resolwe/permissions/models.py
- resolwe/permissions/utils.py
- setup.py
Make it easier to add permissions to objects based on related objects with permissions.
For instance: the storage object is related to the data object so it can inherit the permissions from it.
> Permission refresh

- docs/CHANGELOG.rst
- resolwe/flow/management/commands/test_data_output.py
The command is not finished. There are some issues to resolve.
- some connectors (S3...) store only files and not directories, so directory tests will fail.
- just by iterating through schema it is impossible to tell if reference is a directory and what should that directory contain.
- I could consult the database to check if the entry is a directory or not. If it is I could also obtain the list of all entries in that directory. But let stick with basic file testing for now.
> Add test output management command
