resolwe/flow/tests/__init__.py
The new _debug_info() also returns process' errors and warnings (if they
exist) which will help developers debug their processes.
=> Refactor and augment test's _msg_out() to _debug_info()

docs/CHANGELOG.rst, resolwe/flow/utils/__init__.py, setup.cfg, setup.py, tox.ini
@dblenkus, it would be great if we could include this before the next release.
=> Packaging fixes

resolwe/flow/views.py
Required by [resolwe-py-api PR #2](https://github.com/genialis/resolwe-bio-py/pull/2).
Requires #55.
=> Filter collection by description schema

resolwe/flow/models.py
Fixes the problem with Bowtie 2 in the primary analysis after annotation.
Create collection without slug fixes the New Collection error in the Annotation page.
=> Fix second analysis step in flow collection

docs/CHANGELOG.rst, resolwe/flow/executors/__init__.py, resolwe/flow/models.py, resolwe/flow/tests/__init__.py, setup.py
Add explicit requirement on six package to setup.py
=> Make Resolwe work with Python 3 again

.gitignore, .travis.yml, MANIFEST.in, README.rst, docs/CHANGELOG.rst, resolwe/flow/models.py, resolwe/flow/tests/test_validation.py, setup.cfg, setup.py, tests/settings.py, tox.ini
And general improvements to packaging and tests.
=> Track test coverage with Codecov

resolwe/flow/tests/test_ordering.py, resolwe/flow/views.py
=> Add option to order processes by version

docs/CHANGELOG.rst, resolwe/flow/execution_engines/workflow/__init__.py, resolwe/flow/expression_engines/jinja/filters.py, resolwe/flow/tests/processes/workflow.yml, resolwe/flow/tests/test_executors.py, resolwe/flow/tests/test_expression_filters.py
* Add missing workflow input support.
* Add `data_by_slug` filter.
=> Workflow improvements

docs/CHANGELOG.rst, resolwe/flow/managers/base.py, resolwe/flow/tests/test_env_vars.py, tests/settings.py
TODO: localhost will not work for development, because the server does not run within docker.
=> Export RESOLWE_API_HOST env var in executor

resolwe/flow/models.py, resolwe/flow/tests/test_models.py
=> Trim auto generated data names

resolwe/flow/execution_engines/workflow/__init__.py
NOTE: This change requires re-registration (and manual version bump) of all workflow processes.
=> Add label attribute to steps field in workflows

resolwe/elastic/viewsets.py
=> Increase size parameter in elastic viewset

docs/CHANGELOG.rst, resolwe/elastic/__init__.py, resolwe/elastic/apps.py, resolwe/elastic/builder.py, resolwe/elastic/indices.py, resolwe/elastic/management/commands/elastic_purge.py, resolwe/elastic/tests/test_index.py, resolwe/elastic/tests/test_viewsets.py, resolwe/flow/__init__.py, resolwe/flow/executors/docker.py, resolwe/test/testcases.py, setup.py
Supported Elasticsearch indexes and Docker executor in parallel tests.
TODO:
=> Parallel tests

docs/CHANGELOG.rst, resolwe/test/__init__.py, resolwe/test/testcases.py
Preparatory work for testing if processes can access Resolwe's API host and some general improvements.
=>  Add Resolwe's 'TransactionTestCase' and other improvements

resolwe/flow/expression_engines/jinja/filters.py
Closes https://github.com/genialis/resolwe/issues/226
=> Fix get_url jinja filter

docs/CHANGELOG.rst, docs/ref.rst, resolwe/flow/execution_engines/workflow/__init__.py, resolwe/flow/management/commands/register.py, resolwe/flow/tests/processes/first_version/tests.yml, resolwe/flow/tests/processes/second_version/tests.yml, resolwe/flow/tests/test_api.py, resolwe/flow/tests/test_commands.py, resolwe/flow/tests/test_executors.py, resolwe/flow/views.py, resolwe/permissions/tests/test_utils.py, resolwe/permissions/utils.py
=> Improve permissions handling

MANIFEST.in, docs/CHANGELOG.rst, resolwe/toolkit/docker_images/archiver/Dockerfile, resolwe/toolkit/docker_images/archiver/README.md, resolwe/toolkit/docker_images/base/Dockerfile, resolwe/toolkit/docker_images/base/README.md, resolwe/toolkit/docker_images/upload-tab-file/Dockerfile, resolwe/toolkit/docker_images/upload-tab-file/README.md
=> Add Resolwe toolkit Docker images

MANIFEST.in, resolwe/toolkit/docker_images/base/Dockerfile, resolwe/toolkit/docker_images/base/curlprogress.py, resolwe/toolkit/docker_images/base/re-import.sh
Also add auxiliary `curlprogress.py`.
=> Add re-import and re-checkrc to Resolwe toolkit's base Docker image

docs/CHANGELOG.rst, resolwe/toolkit/processes/archiver.yml
This should fix the bug with archiver. Please review ASAP.
=> Support file lists in archiver

docs/CHANGELOG.rst, resolwe/flow/models/utils.py, resolwe/flow/tests/test_validation.py
=> Validate choices in JSON fields

docs/CHANGELOG.rst, resolwe/elastic/indices.py, resolwe/elastic/tests/test_index.py, resolwe/elastic/tests/test_viewsets.py, resolwe/elastic/viewsets.py
Fixes https://github.com/genialis/bug-reports/issues/24
=> Fix public permissions in elastic app

resolwe/elastic/tests/test_app/elastic_indexes.py, resolwe/elastic/tests/test_app/migrations/0001_initial.py, resolwe/elastic/tests/test_app/models.py, resolwe/elastic/tests/test_app/viewsets.py, resolwe/elastic/tests/test_index.py, resolwe/elastic/tests/test_viewsets.py, resolwe/elastic/viewsets.py
=> Add combined Elastic search + database viewset

resolwe/elastic/tests/test_app/viewsets.py, resolwe/elastic/tests/test_viewsets.py, resolwe/elastic/viewsets.py
=> Fix ordering in combined ES viewset

.travis.yml, docs/proc.rst, resolwe/flow/execution_engines/bash/__init__.py, resolwe/flow/executors/__init__.py, resolwe/flow/executors/docker/__init__.py, resolwe/flow/executors/docker/seccomp.py, resolwe/flow/static/flow/processorSchema.json, resolwe/flow/tests/processes/tests.yml, resolwe/flow/tests/test_access_api.py, resolwe/flow/tests/test_executors.py, tests/settings.py
=> Add resource requirements

docs/CHANGELOG.rst, resolwe/flow/executors/__init__.py, resolwe/flow/tests/test_manager.py, resolwe/test/testcases/__init__.py
Closes https://github.com/genialis/resolwe/issues/290
=> Copy parent's permissions to spawned Data objects

docs/CHANGELOG.rst, docs/contributing.rst, resolwe/__about__.py
@tjanez please merge #303 before the release.
@kostko Do we wait for #306? When will it be ready?
=> Prepare release 1.5.0

resolwe/flow/tests/test_api.py, resolwe/flow/views/entity.py
=> Fix not found error with entity delete content

docs/CHANGELOG.rst, resolwe/flow/tests/test_api.py, resolwe/flow/views/data.py, resolwe/flow/views/mixins.py, resolwe/permissions/tests/test_data.py
=> Mini fixes for Data create view

README.rst, docs/CHANGELOG.rst, docs/contributing.rst
Update README to no longer use lines starting with "From"
=> Remove remaining references to using dependency links

docs/CHANGELOG.rst, docs/proc.rst, resolwe/flow/execution_engines/bash/__init__.py, resolwe/flow/expression_engines/base.py, resolwe/flow/expression_engines/jinja/__init__.py, resolwe/flow/tests/processes/spawned.yml, resolwe/flow/tests/processes/workflow.yml, resolwe/flow/tests/test_expression_filters.py, resolwe/toolkit/processes/archiver.yml, resolwe/toolkit/processes/files.yml, setup.py
This is a **breaking change** that will require fixing of all processes using the `bash` execution engine.
TODO
=> Add input string variable sanitization

docs/CHANGELOG.rst, resolwe/flow/static/flow/fieldSchema.json, resolwe/flow/tests/processes/tests.yml, resolwe/flow/tests/test_commands.py, resolwe/flow/tests/test_validation.py
=> Add basic:url:link to the JSON schema

docs/CHANGELOG.rst, resolwe/elastic/tests/test_viewsets.py, resolwe/permissions/shortcuts.py, resolwe/permissions/tests/test_collection.py
Closes https://github.com/genialis/meta/issues/68
=> Show public objects to logged-in users

docs/CHANGELOG.rst, resolwe/permissions/tests/test_permissions.py, resolwe/permissions/utils.py, tox.ini
=> Return descriptive error for unknown permissions on API

docs/CHANGELOG.rst, resolwe/permissions/tests/test_permissions.py, resolwe/permissions/utils.py
Closes https://github.com/genialis/resolwe/issues/342
=> Return 400 error if permissions are assigned to non-existing user/group

resolwe/flow/management/commands/list_docker_images.py
Previously, we listed all images, including those required for older
versions of processes, which caused problems in deployment (e.g. if
an older image was deleted from dockerhub in the meantime).
This commit changes the `list_docker_images` command to list only
the images required by the latest versions of processes.
=> Fix version handling in 'list_docker_images'

docs/CHANGELOG.rst, resolwe/flow/executors/docker/__init__.py, resolwe/test/testcases/__init__.py
This breaks execution of any `bio-linux8` based Docker image (and possibly any other image, which requires to be run as the root user).
=> Execute Docker container as non-root user

resolwe/__about__.py
Commit fc946f8 introduced a breaking change, therefore we need to bump the major version.
=> Bump version to 3.0.0a1

docs/CHANGELOG.rst, resolwe/elastic/builder.py, resolwe/elastic/indices.py, resolwe/elastic/management/commands/elastic_index.py, resolwe/elastic/tests/test_index.py, resolwe/test/testcases/__init__.py, resolwe/test/testcases/api.py, resolwe/test/testcases/elastic.py, resolwe/test/testcases/process.py, setup.py
=> Add option to build subset of queryset in elasticsearch builder

resolwe/flow/filters.py, resolwe/flow/tests/test_api.py
~Note that this could be an issue for other filters as well and we don't seem to have any tests for filters.~
=> Fix entity collections filter

docs/CHANGELOG.rst, resolwe/permissions/shortcuts.py
Workaround for https://github.com/django-guardian/django-guardian/pull/529
=> Fix guardian's get_groups_with_perms function

resolwe/flow/managers/listener.py
Some events are fired when `Data` objects get their `DONE` status, and these events already need to see spawned children. The changeset in this PR reorders operations in the Resolwe listener so that spawning doesn't happen after finalising anymore.
=> Reorder Data spawning and finalizing in the listener

docs/CHANGELOG.rst, resolwe/flow/models/functions.py, resolwe/flow/models/storage.py, resolwe/flow/models/utils.py, resolwe/flow/tests/test_models.py, resolwe/flow/tests/test_validation.py
=> Add database-side JSON projections for Storage models

docs/CHANGELOG.rst, resolwe/test_helpers/test_runner.py
=> Address missed review comments

docs/CHANGELOG.rst, resolwe/flow/executors/docker/run.py, resolwe/flow/executors/prepare.py, resolwe/flow/executors/run.py, resolwe/flow/management/commands/collecttools.py, resolwe/flow/tests/test_executors.py, resolwe/flow/utils/__init__.py
=> Add management command for collecting tools

resolwe/elastic/fields.py, resolwe/elastic/lookup.py, resolwe/elastic/signals.py, resolwe/elastic/tests/test_app/viewsets.py, resolwe/elastic/tests/test_viewsets.py, resolwe/elastic/viewsets.py, resolwe/flow/elastic_indexes/base.py, resolwe/flow/elastic_indexes/data.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/data.py, resolwe/test/testcases/__init__.py
Also adds support for configuring filter field maps.
=> Add edge n-gram indexes to various data fields

resolwe/flow/managers/consumer.py, resolwe/flow/managers/dispatcher.py, resolwe/flow/managers/listener.py
Communicate calls weren't protected by a counter claim, so it could
happen that a communicate command was issued, then the synchronization
counter dropped to 0 before the command was picked up by Channels on the
other side. Fixed by increasing the count when the command is generated,
and decreasing it once the _data_scan function finishes.
There was also a problem with parallel testing. The Channels Redis layer
is global (per server) and its flush command clears all asgi-related
channels from the server. In the case of parallelized test suites, this
means that one process can still be doing work while another finished -
upon finishing, it will "clean up after itself" by flushing, which will
also clean keys used by other testing processes, interrupting their flow
and likely hanging them …
=> Fix premature counter zeroing and aggressive Channels flushing in tests

resolwe/toolkit/processes/archiver.yml, resolwe/toolkit/processes/files.yml
Updated processes: archiver, upload-file, upload-image-file and
upload-tab-file.
=> Fix process name, description, category and requirements

resolwe/flow/managers/dispatcher.py, resolwe/storage/apps.py, resolwe/storage/connectors/registry.py, resolwe/storage/manager.py, resolwe/storage/settings.py, resolwe/storage/tests/test_manager.py, resolwe/test_helpers/test_runner.py, tests/settings.py
and add sensible default if they are not available in global settings.
=> Change storage settings

tests/docker-compose.yml, tests/settings.py
And make it configurable through environment variable.
=> Use default password for database connections

docs/storage.rst, resolwe/storage/cleanup.py, resolwe/storage/connectors/baseconnector.py, resolwe/storage/connectors/googleconnector.py, resolwe/storage/connectors/localconnector.py, resolwe/storage/connectors/s3connector.py, resolwe/storage/settings.py, resolwe/storage/tests/storage_credentials_test_connectors.py, resolwe/storage/views.py
Validate arguments to the delete methed and make sure connector can not
perform operation outsde  its base_path.
Also fix cleanup bug that could potentially delete data belonging to
other storage locations and make sure StorageLocation is not deleted
if its data was not successfully removed.
=> Make delete safer

resolwe/storage/connectors/transfer.py
when it fails. If transfer fails multiple times abort.
=> Retry file transfer

resolwe/storage/connectors/googleconnector.py, setup.py
=> Generate virtual-host-style signed URLs

docs/CHANGELOG.rst, resolwe/flow/executors/__main__.py, resolwe/flow/executors/null/run.py, resolwe/flow/executors/run.py, resolwe/flow/tests/test_executors.py, resolwe/storage/connectors/googleconnector.py
Otherwise exception is thrown.
=> Fix duplicated bug and batch upload

docs/CHANGELOG.rst, resolwe/flow/managers/listener.py, resolwe/storage/tests/test_listener.py
when it is downloaded by the executor.
=> Add referenced files to storage location

docs/CHANGELOG.rst, resolwe/flow/execution_engines/python/__init__.py, resolwe/flow/models/__init__.py, resolwe/flow/models/utils.py, resolwe/flow/tests/test_models.py, resolwe/process/__main__.py, resolwe/process/descriptor.py, resolwe/process/fields.py, resolwe/process/runtime.py, resolwe/process/tests/processes/python_test.py, resolwe/process/tests/test_python_process.py
@dblenkus , @gregorjerse This is heavily WIP, but it would be great if you could provide some general feedback regarding the approach i took.
=> Relations in Python process

resolwe/flow/models/utils/duplicate.py
- Skip pre-processing of objects
- Handle case where collection or entity is not set
=> Fix bulk_duplicate function

docs/CHANGELOG.rst, resolwe/flow/managers/dispatcher.py, resolwe/flow/managers/state.py, resolwe/flow/tests/test_manager.py, resolwe/flow/tests/test_relations.py, resolwe/flow/views/relation.py
if he has view permission on the respective collection.
=> Make relations visible to public user

docs/CHANGELOG.rst, resolwe/flow/tests/files/processes/test_python.py, resolwe/flow/utils/docs/autoprocess.py, resolwe/process/descriptor.py, resolwe/process/parser.py
=> Support Python processes in Sphinx autoprocess directive

.github/workflows/ci.yml, .github/workflows/docker.yml
in order to build prereleases automatically.
=> Change tag regexp

resolwe/flow/managers/listener.py, resolwe/flow/tests/test_executors.py
and remove debug output from the listener.
=> Fix randomly failing test

resolwe/flow/execution_engines/python/__init__.py, resolwe/flow/executors/collect.py, resolwe/flow/executors/docker/run.py, resolwe/flow/executors/null/prepare.py, resolwe/flow/executors/prepare.py, resolwe/flow/executors/transfer.py, resolwe/flow/managers/__init__.py, resolwe/flow/managers/dispatcher.py, resolwe/flow/managers/listener/__init__.py, resolwe/flow/managers/listener/basic_commands_plugin.py, resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/listener/plugin.py, resolwe/flow/managers/listener/python_process_plugin.py, resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/flow/models/process.py, resolwe/flow/models/utils/reference.py, resolwe/flow/tests/test_executors.py, resolwe/flow/tests/test_models.py, resolwe/process/__main__.py, resolwe/process/fields.py, resolwe/process/models.py, resolwe/process/parser.py, resolwe/process/runtime.py, resolwe/process/runtimes.py, resolwe/storage/tests/test_listener.py, resolwe/test_helpers/test_runner.py, tests/settings.py
So one can add custom command handlers in other projects, such as
resolwe-bio.
=> Listener plugins & python process extensions & failing e2e tests

resolwe/storage/views.py
@dblenkus @gregorjerse Please take a look and comment whether the approach seems fine.
=> Add UriResolverView

resolwe/flow/executors/docker/run.py, resolwe/flow/executors/init_container.py, resolwe/flow/executors/logger.py, resolwe/flow/executors/socket_utils.py, resolwe/flow/executors/startup_communication_container.py, resolwe/flow/executors/startup_processing_container.py, resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/workload_connectors/local.py, resolwe/flow/tests/test_executors.py
also make sure the log files do not change while uploading else file
descriptor will close and transfer error will occur.
=> Do not block async loop while uploading log files

resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/flow/tests/test_utils.py
or job wont start if the label is too long for instance.
=> Sanitize kubernetes label

resolwe/flow/managers/workload_connectors/kubernetes.py
Increase EBS size by 10% to account for file system overhead on very
large input volumes.
=> Handle very large inputs correctly

resolwe/storage/tests/test_views.py, resolwe/storage/views.py
This solves the issue with too long request URL when there are
100+ URIs to resolve.
=> Rewrite UriResolverView to work with POST requests

resolwe/flow/executors/socket_utils.py, resolwe/flow/managers/dispatcher.py, resolwe/storage/settings.py
to make build_sphinx command work
=> Add default value to PROJECT_ROOT if not present

resolwe/flow/executors/startup_communication_container.py, resolwe/storage/connectors/transfer.py
Add support for hashes and flag indicationg push preserves data integrity when uploading files in containers.
=> Transfer in communication container

resolwe/flow/management/commands/cleantestdir.py, resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/storage/connectors/s3connector.py
- Remove unused session token from S3 connector credentials 
- Remove line of kode from kubernetes causing storage limits to be ignored
- Fix cleantestdirs to only clean volumes of type ``host_path``
=> Features & fixes

resolwe/storage/models.py, resolwe/storage/tests/test_models.py
otherwise django.db.utils.IntegrityError is thrown due to duplicated
primary key.
=> Create ReferencedPath only when needed

resolwe/storage/cleanup.py
so that basic information is logged to level INFO.
=> Improve logging in cleanup manager

docs/CHANGELOG.rst, resolwe/process/fields.py, resolwe/process/tests/processes/python_test.py, resolwe/process/tests/test_python_process.py
This PR adds support for range parameter in Fields of python processes.
=> Support range in fields of Python proces

resolwe/flow/tests/test_executors.py, resolwe/permissions/models.py
When transaction is aborted due to slug colision the PermissionGroup is
also destroyed in the database. It is still attached to the object as
property and additional check is needed to create it again if necessary.
=> Fix: create new permission group on rollback

docs/CHANGELOG.rst, resolwe/flow/tests/test_executors.py
using mock object to mock pre_save method.
=> Create nicer slug colision test

docs/CHANGELOG.rst, resolwe/flow/managers/listener/python_process_plugin.py, resolwe/process/tests/processes/python_test.py, resolwe/process/tests/test_python_process.py
when checking permissions in python process
=> Do not return multiple versions of the same process

docs/CHANGELOG.rst, resolwe/process/fields.py, resolwe/storage/views.py
if status code indicating error was received from the upstream server
=> Fix misleading error message on file import

resolwe/flow/managers/workload_connectors/kubernetes.py
First try to load credentials from file and then from incluster config.
=> Change credentials loading order

resolwe/flow/executors/docker/run.py, resolwe/flow/executors/prepare.py, resolwe/flow/executors/run.py, resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/workload_connectors/kubernetes.py
as environmental variable and append it to the path in the script sent
by the listener.
=> Generate tools mount paths in the executor

resolwe/flow/models/utils/hydrate.py
=> Add s3 url to urlregex

.github/workflows/docker.yml, docs/CHANGELOG.rst, resolwe/toolkit/docker_images/base/Dockerfile.fedora-36, resolwe/toolkit/docker_images/base/Dockerfile.ubuntu-22.04, resolwe/toolkit/docker_images/base/README.md
to Ubuntu 22.04 and Fedora 36.
=> Upgrade base docker containers

docs/CHANGELOG.rst, resolwe/flow/managers/listener/python_process_plugin.py, resolwe/flow/models/base.py
=> Retry creating object in listener on slug colision

docs/CHANGELOG.rst, resolwe/flow/tests/test_filtering.py, resolwe/flow/views/data.py
=> Allow sorting data endpoint by entity name

docs/CHANGELOG.rst, resolwe/observers/consumers.py
=> Remove call to close that caused RuntimeError

resolwe/flow/executors/startup_processing_container.py, resolwe/flow/management/commands/runlistener.py, setup.py
EXP-551
EXP-593
EXP-607
EXP-612
=> Fix script retrieval timeout & replace asyncio loop with uvloop

docs/CHANGELOG.rst, resolwe/flow/managers/workload_connectors/kubernetes.py, tests/settings.py
=> Enable setting affinity for interactive/batch processes

docs/CHANGELOG.rst, resolwe/flow/managers/workload_connectors/kubernetes.py, tests/settings.py
via the settings variable.
EXP-617
EXP-565
=> Make kubernetes overcommitment factors configurable

docs/CHANGELOG.rst, resolwe/flow/filters.py, resolwe/flow/tests/test_filtering.py
=> Filter by tags on Relation API

docs/CHANGELOG.rst, resolwe/flow/models/collection.py, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/flow/tests/test_models.py, resolwe/observers/consumers.py, resolwe/observers/utils.py, resolwe/observers/views.py, resolwe/test_helpers/test_runner.py, setup.py
and add detailview to backgroundtask endpoint.
=> Start backgroundtaskconsumer when running tests

docs/CHANGELOG.rst, resolwe/test_helpers/test_runner.py
if the same test is in the changed test file and tagged.
BUG-944
=> Do not run the test twice

docs/CHANGELOG.rst
=> Prepare release 34.0.0

docs/CHANGELOG.rst, resolwe/api_urls.py, resolwe/flow/managers/consumer.py, resolwe/observers/consumers.py, resolwe/observers/signals.py, resolwe/observers/tests.py
=> Expose annotation endpoints and send observer create on duplication

docs/CHANGELOG.rst, resolwe/flow/models/collection.py, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/observers/consumers.py, resolwe/observers/tests.py, resolwe/observers/utils.py, resolwe/observers/views.py
=> Fix background task permissions and add filtering by id

resolwe/observers/utils.py, resolwe/test_helpers/test_runner.py
=> Use background context manager singleton

docs/CHANGELOG.rst, resolwe/flow/models/collection.py, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/collection.py, resolwe/flow/views/data.py, resolwe/flow/views/mixins.py, resolwe/observers/consumers.py, resolwe/observers/tests.py, resolwe/permissions/tests/test_collection.py, resolwe/permissions/tests/test_data.py
in data, entity and collection endpoints
EXP-631
EXP-632
=> API calls delete objects in the background

docs/CHANGELOG.rst, setup.py
https://github.com/docker/docker-py/issues/3113
BUG-966
=> Bump docker version to fix requests/urllib bug

docs/CHANGELOG.rst, resolwe/observers/consumers.py
=> Close websocket requests without session id

docs/CHANGELOG.rst, resolwe/flow/executors/socket_utils.py, resolwe/flow/managers/listener/basic_commands_plugin.py, resolwe/flow/managers/listener/bootstrap_plugin.py, resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/listener/permission_plugin.py, resolwe/flow/managers/listener/plugin.py, resolwe/flow/managers/listener/plugin_interface.py, resolwe/flow/managers/listener/python_process_plugin.py, resolwe/flow/managers/listener/redis_cache.py, resolwe/flow/tests/test_executors.py, resolwe/flow/tests/test_redis_cache.py, resolwe/storage/tests/test_listener.py, resolwe/test/testcases/__init__.py
so it can be used to cache Feature objects to speed up slow queries.
EXP-611
=> Generalize Redis cache

docs/CHANGELOG.rst, resolwe/flow/tests/test_annotations.py, resolwe/flow/views/collection.py
Replace add_fields_to_collection and remove_fields_from_collection with set_annotation_fields method
=> Change setting annotation fields on collection

docs/CHANGELOG.rst, resolwe/flow/serializers/relation.py, resolwe/flow/tests/test_relations.py
=> Add slug to relation serializer

docs/CHANGELOG.rst, resolwe/storage/connectors/s3connector.py
=> Fix invalid filename when downloading file

docs/CHANGELOG.rst, resolwe/flow/serializers/relation.py, resolwe/flow/tests/test_relations.py
=> Make relation slug writeable

docs/CHANGELOG.rst, resolwe/flow/tests/test_filtering.py, resolwe/flow/views/collection.py
=> Allow sorting entities by collection name

.github/workflows/ci.yml, resolwe/flow/models/annotations.py, resolwe/flow/tests/test_annotations.py
that was previously removed by mistake. Make it also more efficient.
=> Add label_by_value method

docs/CHANGELOG.rst, resolwe/flow/executors/docker/run.py, resolwe/flow/executors/run.py, resolwe/flow/managers/dispatcher.py, resolwe/flow/managers/listener/redis_cache.py, resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/flow/models/data.py, resolwe/flow/models/utils/__init__.py, resolwe/flow/models/utils/duplicate.py, resolwe/flow/tests/processes/workflow.yml, resolwe/flow/tests/test_api.py, resolwe/flow/tests/test_executors.py, resolwe/flow/tests/test_models.py, resolwe/flow/views/data.py, resolwe/observers/consumers.py, resolwe/observers/signals.py, resolwe/permissions/mixins.py, resolwe/permissions/shortcuts.py, resolwe/process/runtime.py
=> Restart data object

docs/CHANGELOG.rst, resolwe/flow/filters.py, resolwe/flow/models/annotations.py, resolwe/flow/tests/test_annotations.py, resolwe/flow/views/annotations.py, resolwe/permissions/utils.py
=> Simplify permission checks on AnnotationValue endpoint

docs/CHANGELOG.rst, resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/flow/models/history.py
=> Fix create history object for collection

docs/CHANGELOG.rst, resolwe/flow/admin.py
to admin page for AnnotationField objects
=> Add custom filtering and searching

docs/CHANGELOG.rst, resolwe/flow/managers/listener/listener.py, tests/settings.py
in the listener via environmental variable
=> Allow overriding max_concurrent_commands

docs/CHANGELOG.rst, resolwe/flow/models/fields.py, resolwe/flow/tests/test_fields.py, resolwe/flow/tests/test_purge.py, resolwe/test/testcases/process.py
=> Fix user defined slug must not be changed

docs/CHANGELOG.rst, resolwe/flow/managers/listener/listener.py, resolwe/flow/models/annotations.py, resolwe/flow/tests/test_annotations.py, resolwe/flow/tests/test_executors.py, resolwe/storage/tests/test_listener.py
Also make annotation field path checking more robust
REID-2124
=> Raise ValidationError if field path is invalid

resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/listener/python_process_plugin.py, resolwe/flow/models/annotations.py, resolwe/flow/models/entity.py, resolwe/flow/views/entity.py
and refactor updating annotations.
=> Fix lock in the listener

docs/CHANGELOG.rst, resolwe/flow/managers/listener/redis_cache.py, resolwe/flow/models/data.py, resolwe/flow/tests/test_redis_cache.py
=> Fix data restart

docs/CHANGELOG.rst, resolwe/flow/management/commands/clear_redis_cache.py
=> Add clear_redis_cache management command

docs/CHANGELOG.rst, resolwe/flow/models/data.py
=> Correctly enumerate dependencies when restarting a data object

docs/CHANGELOG.rst, resolwe/flow/models/annotations.py, resolwe/flow/models/entity.py, resolwe/flow/models/utils/duplicate.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/entity.py
=> Handle annotations when moving/copying entities

.github/workflows/ci.yml, docs/CHANGELOG.rst, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/data.py, resolwe/flow/views/entity.py, resolwe/observers/consumers.py
=> Make move between collections a background job

docs/CHANGELOG.rst, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/data.py, resolwe/flow/views/entity.py, resolwe/observers/consumers.py
This reverts commit 9f0e36b41f305779614c88935d8b1f3640562557.
=> Revert "Make move between collections a background job"

docs/CHANGELOG.rst, resolwe/flow/models/data.py, resolwe/flow/models/entity.py, resolwe/flow/tests/test_api.py, resolwe/flow/views/data.py, resolwe/flow/views/entity.py, resolwe/observers/consumers.py
This reverts commit 4c6b1b3c76b12a0471b5335cc854c6ee683787bd.
=> Reapply "Make move between collections a background job"

resolwe/flow/managers/listener/listener.py, resolwe/flow/managers/workload_connectors/celery.py, resolwe/flow/managers/workload_connectors/kubernetes.py, resolwe/flow/tasks.py
to send encryption key to the executor
=> Fix celery workload connector

resolwe/storage/utils.py, resolwe/storage/views.py
=> Return date in RFC-3339 fromat on upload credentials endpoint

.github/workflows/ci.yml, tests/settings.py
=> Use debug in github actions on demand

docs/CHANGELOG.rst, resolwe/flow/managers/listener/metrics.py, tests/settings.py
via environmental variable METRIC_EXPORT_SIZE
=> Allow setting metrics point exported in a batch

docs/CHANGELOG.rst, resolwe/flow/managers/workload_connectors/kubernetes.py
=> Restrict permissions used by processing container

docs/CHANGELOG.rst, resolwe/flow/models/annotations.py, resolwe/flow/tests/test_annotations.py
when removing the delete markers
=> Fix crash in annotation value endpoint

docs/CHANGELOG.rst, resolwe/flow/executors/init_container.py
and reduce them to 3 by default.
=> Make number of download threads configurable

.github/workflows/ci.yml
=> Use public docker runner in CI workflow

.github/workflows/docker.yml
=> Authenticate docker workflow using Github OIDC

resolwe/observers/consumers.py
to make sure delete method is called
=> Do not bulk delete subsciptions

docs/CHANGELOG.rst, resolwe/api_urls.py, resolwe/flow/models/process.py, resolwe/process/resources.py, resolwe/process/tests/processes/python_test.py, resolwe/process/tests/test_python_process.py
=> Dynamic resources

docs/CHANGELOG.rst, resolwe/flow/views/annotations.py
in annotation value viewset
REID-2765
=> Prefetch contributor data

.github/workflows/ci.yml, pyproject.toml
=> Fix coverage upload and pin Django to 5.1.x

docs/CHANGELOG.rst, pyproject.toml, resolwe/flow/models/__init__.py, resolwe/permissions/tests/test_collection.py, resolwe/permissions/tests/test_data.py
=> Bump Django version to 5.2.0

pyproject.toml
and remove upper Python limit.
=> Fix remove unsupported Python version

docs/CHANGELOG.rst, resolwe/flow/filters.py, resolwe/flow/tests/test_filtering.py, resolwe/flow/views/entity.py, tests/settings.py
and consolidate all ordering into single order filter.
=> Move ordering by annotatitons to order filter

docs/CHANGELOG.rst, resolwe/flow/serializers/annotations.py, resolwe/flow/tests/test_annotations.py, resolwe/flow/views/collection.py
Make method general so it can be used to assign prediction fields also.
REID-2753
=> Generic assign annotation to collection
